services:
  gateway:
    build: ./Gateway
    environment:
      - ASPNETCORE_URLS=http://+:5000
    ports:
      - "8080:5000"
    depends_on:
      authenticationservice:
        condition: service_healthy

  authenticationservice:
    build: ./AuthenticationService
    deploy:
      replicas: 1
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__Default=${CONNECTIONSTRING_DEFAULT}
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:5000/health"]
      interval: 5s
      timeout: 3s
      retries: 20
    # Note: this service no longer depends on a local MySQL container.
    # The authentication service reads the connection string from
    # the env variable ConnectionStrings__Default (populated from
    # the .env file as CONNECTIONSTRING_DEFAULT).

volumes:
  dbdata:
