version: "3.9"

services:
  gateway:
    build: ./Gateway
    environment:
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - "8080:8080"
    depends_on:
      authenticationservice:
        condition: service_healthy
    networks:
      - appnet

  authenticationservice:
    build: ./AuthenticationService
    environment:
      - ASPNETCORE_URLS=http://+:5000
      # Connection string til din online database:
      - ConnectionStrings__Default=Server=mysql73.unoeuro.com;Port=3306;Database=ferrariconnie_dk_db;Uid=ferrariconnie_dk;Pwd=bkngcw5BmR6DEx2ep4a3;
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:5000/health"]
      interval: 5s
      timeout: 3s
      retries: 20
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
