services:
  gateway:
    build: ./Gateway
    environment:
      - ASPNETCORE_URLS=http://+:5000
    ports:
      - "8080:5000"
    depends_on:
      authenticationservice:
        condition: service_healthy

  authenticationservice:
    build: ./AuthenticationService
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__Default=server=usersdb;user=root;password=root;database=usersdb
    ports:
        - "8080:5000"
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:5000/health"]
      interval: 5s
      timeout: 3s
      retries: 20
    depends_on:
      usersdb:
        condition: service_healthy

  usersdb:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: usersdb
    # ⇩ vigtig: persistér data + kør init.sql ved første opstart
    volumes:
      - dbdata:/var/lib/mysql
      - ./AuthenticationService/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    # ⇩ vigtig: eksponér MySQL til din host, så HeidiSQL kan forbinde
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  dbdata:
